//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://EcUtbildning.generatestuff", ConfigurationName="IString")]
public interface IString
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://EcUtbildning.generatestuff/IString/mystuff", ReplyAction="http://EcUtbildning.generatestuff/IString/mystuffResponse")]
    string mystuff(string stuff);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://EcUtbildning.generatestuff/IString/mystuff", ReplyAction="http://EcUtbildning.generatestuff/IString/mystuffResponse")]
    System.Threading.Tasks.Task<string> mystuffAsync(string stuff);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IStringChannel : IString, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class StringClient : System.ServiceModel.ClientBase<IString>, IString
{
    
    public StringClient()
    {
    }
    
    public StringClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public StringClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public StringClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public StringClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string mystuff(string stuff)
    {
        return base.Channel.mystuff(stuff);
    }
    
    public System.Threading.Tasks.Task<string> mystuffAsync(string stuff)
    {
        return base.Channel.mystuffAsync(stuff);
    }
}
