//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://EcUtbildning.generatestuff", ConfigurationName="IBMI")]
public interface IBMI
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://EcUtbildning.generatestuff/IBMI/BMI", ReplyAction="http://EcUtbildning.generatestuff/IBMI/BMIResponse")]
    int BMI(int a, int b);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://EcUtbildning.generatestuff/IBMI/BMI", ReplyAction="http://EcUtbildning.generatestuff/IBMI/BMIResponse")]
    System.Threading.Tasks.Task<int> BMIAsync(int a, int b);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IBMIChannel : IBMI, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class BMIClient : System.ServiceModel.ClientBase<IBMI>, IBMI
{
    
    public BMIClient()
    {
    }
    
    public BMIClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public BMIClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BMIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BMIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public int BMI(int a, int b)
    {
        return base.Channel.BMI(a, b);
    }
    
    public System.Threading.Tasks.Task<int> BMIAsync(int a, int b)
    {
        return base.Channel.BMIAsync(a, b);
    }
}
